spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.137:3306/item
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
server:
  port: 8080
  servlet:
    context-path: /app
